package models

const (
	LEDGER_TYPE_ASSET     = "ASSET"
	LEDGER_TYPE_EXPENSE   = "EXPENSE"
	LEDGER_TYPE_LIABILITY = "LIABILITY"
	LEDGER_TYPE_INCOME    = "INCOME"
	LEDGER_TYPE_CAPITAL   = "CAPITAL"
)
