// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ledger.proto

package ledger

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LedgerType int32

const (
	LedgerType_ASSET     LedgerType = 0
	LedgerType_LIABILITY LedgerType = 1
	LedgerType_INCOME    LedgerType = 2
	LedgerType_EXPENSE   LedgerType = 3
	LedgerType_CAPITAL   LedgerType = 4
)

var LedgerType_name = map[int32]string{
	0: "ASSET",
	1: "LIABILITY",
	2: "INCOME",
	3: "EXPENSE",
	4: "CAPITAL",
}
var LedgerType_value = map[string]int32{
	"ASSET":     0,
	"LIABILITY": 1,
	"INCOME":    2,
	"EXPENSE":   3,
	"CAPITAL":   4,
}

func (x LedgerType) String() string {
	return proto.EnumName(LedgerType_name, int32(x))
}
func (LedgerType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ledger_eb4c17c6264da805, []int{0}
}

type Any struct {
	TypeUrl              string   `protobuf:"bytes,1,opt,name=type_url,json=typeUrl,proto3" json:"type_url,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Any) Reset()         { *m = Any{} }
func (m *Any) String() string { return proto.CompactTextString(m) }
func (*Any) ProtoMessage()    {}
func (*Any) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledger_eb4c17c6264da805, []int{0}
}
func (m *Any) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Any.Unmarshal(m, b)
}
func (m *Any) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Any.Marshal(b, m, deterministic)
}
func (dst *Any) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Any.Merge(dst, src)
}
func (m *Any) XXX_Size() int {
	return xxx_messageInfo_Any.Size(m)
}
func (m *Any) XXX_DiscardUnknown() {
	xxx_messageInfo_Any.DiscardUnknown(m)
}

var xxx_messageInfo_Any proto.InternalMessageInfo

func (m *Any) GetTypeUrl() string {
	if m != nil {
		return m.TypeUrl
	}
	return ""
}

func (m *Any) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SearchRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchRequest) Reset()         { *m = SearchRequest{} }
func (m *SearchRequest) String() string { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()    {}
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledger_eb4c17c6264da805, []int{1}
}
func (m *SearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchRequest.Unmarshal(m, b)
}
func (m *SearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchRequest.Marshal(b, m, deterministic)
}
func (dst *SearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchRequest.Merge(dst, src)
}
func (m *SearchRequest) XXX_Size() int {
	return xxx_messageInfo_SearchRequest.Size(m)
}
func (m *SearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SearchRequest proto.InternalMessageInfo

func (m *SearchRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type Ledger struct {
	Reference            string          `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Type                 LedgerType      `protobuf:"varint,2,opt,name=type,proto3,enum=ledger.LedgerType" json:"type,omitempty"`
	Parent               string          `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Data                 map[string]*Any `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Ledger) Reset()         { *m = Ledger{} }
func (m *Ledger) String() string { return proto.CompactTextString(m) }
func (*Ledger) ProtoMessage()    {}
func (*Ledger) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledger_eb4c17c6264da805, []int{2}
}
func (m *Ledger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ledger.Unmarshal(m, b)
}
func (m *Ledger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ledger.Marshal(b, m, deterministic)
}
func (dst *Ledger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ledger.Merge(dst, src)
}
func (m *Ledger) XXX_Size() int {
	return xxx_messageInfo_Ledger.Size(m)
}
func (m *Ledger) XXX_DiscardUnknown() {
	xxx_messageInfo_Ledger.DiscardUnknown(m)
}

var xxx_messageInfo_Ledger proto.InternalMessageInfo

func (m *Ledger) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *Ledger) GetType() LedgerType {
	if m != nil {
		return m.Type
	}
	return LedgerType_ASSET
}

func (m *Ledger) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Ledger) GetData() map[string]*Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type Account struct {
	Reference            string          `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	Currency             string          `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	Ledger               string          `protobuf:"bytes,3,opt,name=ledger,proto3" json:"ledger,omitempty"`
	Balance              int64           `protobuf:"varint,4,opt,name=balance,proto3" json:"balance,omitempty"`
	Data                 map[string]*Any `protobuf:"bytes,5,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledger_eb4c17c6264da805, []int{3}
}
func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (dst *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(dst, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *Account) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Account) GetLedger() string {
	if m != nil {
		return m.Ledger
	}
	return ""
}

func (m *Account) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *Account) GetData() map[string]*Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type TransactionEntry struct {
	Account              string   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionEntry) Reset()         { *m = TransactionEntry{} }
func (m *TransactionEntry) String() string { return proto.CompactTextString(m) }
func (*TransactionEntry) ProtoMessage()    {}
func (*TransactionEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledger_eb4c17c6264da805, []int{4}
}
func (m *TransactionEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionEntry.Unmarshal(m, b)
}
func (m *TransactionEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionEntry.Marshal(b, m, deterministic)
}
func (dst *TransactionEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionEntry.Merge(dst, src)
}
func (m *TransactionEntry) XXX_Size() int {
	return xxx_messageInfo_TransactionEntry.Size(m)
}
func (m *TransactionEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionEntry.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionEntry proto.InternalMessageInfo

func (m *TransactionEntry) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *TransactionEntry) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type Transaction struct {
	Reference            string              `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	TransactedAt         string              `protobuf:"bytes,2,opt,name=transacted_at,json=transactedAt,proto3" json:"transacted_at,omitempty"`
	Data                 map[string]*Any     `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Entries              []*TransactionEntry `protobuf:"bytes,4,rep,name=entries,proto3" json:"entries,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_ledger_eb4c17c6264da805, []int{5}
}
func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (dst *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(dst, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetReference() string {
	if m != nil {
		return m.Reference
	}
	return ""
}

func (m *Transaction) GetTransactedAt() string {
	if m != nil {
		return m.TransactedAt
	}
	return ""
}

func (m *Transaction) GetData() map[string]*Any {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Transaction) GetEntries() []*TransactionEntry {
	if m != nil {
		return m.Entries
	}
	return nil
}

func init() {
	proto.RegisterType((*Any)(nil), "ledger.Any")
	proto.RegisterType((*SearchRequest)(nil), "ledger.SearchRequest")
	proto.RegisterType((*Ledger)(nil), "ledger.Ledger")
	proto.RegisterMapType((map[string]*Any)(nil), "ledger.Ledger.DataEntry")
	proto.RegisterType((*Account)(nil), "ledger.Account")
	proto.RegisterMapType((map[string]*Any)(nil), "ledger.Account.DataEntry")
	proto.RegisterType((*TransactionEntry)(nil), "ledger.TransactionEntry")
	proto.RegisterType((*Transaction)(nil), "ledger.Transaction")
	proto.RegisterMapType((map[string]*Any)(nil), "ledger.Transaction.DataEntry")
	proto.RegisterEnum("ledger.LedgerType", LedgerType_name, LedgerType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LedgerServiceClient interface {
	// Searches for an ledger based on details
	SearchLedgers(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (LedgerService_SearchLedgersClient, error)
	// Creates a new ledger based on supplied data
	CreateLedger(ctx context.Context, in *Ledger, opts ...grpc.CallOption) (*Ledger, error)
	// Updates the data component of the ledger.
	UpdateLedger(ctx context.Context, in *Ledger, opts ...grpc.CallOption) (*Ledger, error)
	// Searches for an account based on details
	SearchAccounts(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (LedgerService_SearchAccountsClient, error)
	// Creates a new account based on supplied data
	CreateAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error)
	// Updates the data component of the account.
	UpdateAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error)
	// Searches for a transaction based on details
	SearchTransactions(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (LedgerService_SearchTransactionsClient, error)
	// Creates a new transaction
	CreateTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Transaction, error)
	// Creates a new transaction
	ReverseTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Transaction, error)
	// Updates a transaction's details
	UpdateTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Transaction, error)
}

type ledgerServiceClient struct {
	cc *grpc.ClientConn
}

func NewLedgerServiceClient(cc *grpc.ClientConn) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) SearchLedgers(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (LedgerService_SearchLedgersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LedgerService_serviceDesc.Streams[0], "/ledger.LedgerService/SearchLedgers", opts...)
	if err != nil {
		return nil, err
	}
	x := &ledgerServiceSearchLedgersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LedgerService_SearchLedgersClient interface {
	Recv() (*Ledger, error)
	grpc.ClientStream
}

type ledgerServiceSearchLedgersClient struct {
	grpc.ClientStream
}

func (x *ledgerServiceSearchLedgersClient) Recv() (*Ledger, error) {
	m := new(Ledger)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ledgerServiceClient) CreateLedger(ctx context.Context, in *Ledger, opts ...grpc.CallOption) (*Ledger, error) {
	out := new(Ledger)
	err := c.cc.Invoke(ctx, "/ledger.LedgerService/CreateLedger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) UpdateLedger(ctx context.Context, in *Ledger, opts ...grpc.CallOption) (*Ledger, error) {
	out := new(Ledger)
	err := c.cc.Invoke(ctx, "/ledger.LedgerService/UpdateLedger", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) SearchAccounts(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (LedgerService_SearchAccountsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LedgerService_serviceDesc.Streams[1], "/ledger.LedgerService/SearchAccounts", opts...)
	if err != nil {
		return nil, err
	}
	x := &ledgerServiceSearchAccountsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LedgerService_SearchAccountsClient interface {
	Recv() (*Account, error)
	grpc.ClientStream
}

type ledgerServiceSearchAccountsClient struct {
	grpc.ClientStream
}

func (x *ledgerServiceSearchAccountsClient) Recv() (*Account, error) {
	m := new(Account)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ledgerServiceClient) CreateAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/ledger.LedgerService/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) UpdateAccount(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := c.cc.Invoke(ctx, "/ledger.LedgerService/UpdateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) SearchTransactions(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (LedgerService_SearchTransactionsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LedgerService_serviceDesc.Streams[2], "/ledger.LedgerService/SearchTransactions", opts...)
	if err != nil {
		return nil, err
	}
	x := &ledgerServiceSearchTransactionsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LedgerService_SearchTransactionsClient interface {
	Recv() (*Transaction, error)
	grpc.ClientStream
}

type ledgerServiceSearchTransactionsClient struct {
	grpc.ClientStream
}

func (x *ledgerServiceSearchTransactionsClient) Recv() (*Transaction, error) {
	m := new(Transaction)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *ledgerServiceClient) CreateTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, "/ledger.LedgerService/CreateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) ReverseTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, "/ledger.LedgerService/ReverseTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) UpdateTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, "/ledger.LedgerService/UpdateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServiceServer is the server API for LedgerService service.
type LedgerServiceServer interface {
	// Searches for an ledger based on details
	SearchLedgers(*SearchRequest, LedgerService_SearchLedgersServer) error
	// Creates a new ledger based on supplied data
	CreateLedger(context.Context, *Ledger) (*Ledger, error)
	// Updates the data component of the ledger.
	UpdateLedger(context.Context, *Ledger) (*Ledger, error)
	// Searches for an account based on details
	SearchAccounts(*SearchRequest, LedgerService_SearchAccountsServer) error
	// Creates a new account based on supplied data
	CreateAccount(context.Context, *Account) (*Account, error)
	// Updates the data component of the account.
	UpdateAccount(context.Context, *Account) (*Account, error)
	// Searches for a transaction based on details
	SearchTransactions(*SearchRequest, LedgerService_SearchTransactionsServer) error
	// Creates a new transaction
	CreateTransaction(context.Context, *Transaction) (*Transaction, error)
	// Creates a new transaction
	ReverseTransaction(context.Context, *Transaction) (*Transaction, error)
	// Updates a transaction's details
	UpdateTransaction(context.Context, *Transaction) (*Transaction, error)
}

func RegisterLedgerServiceServer(s *grpc.Server, srv LedgerServiceServer) {
	s.RegisterService(&_LedgerService_serviceDesc, srv)
}

func _LedgerService_SearchLedgers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LedgerServiceServer).SearchLedgers(m, &ledgerServiceSearchLedgersServer{stream})
}

type LedgerService_SearchLedgersServer interface {
	Send(*Ledger) error
	grpc.ServerStream
}

type ledgerServiceSearchLedgersServer struct {
	grpc.ServerStream
}

func (x *ledgerServiceSearchLedgersServer) Send(m *Ledger) error {
	return x.ServerStream.SendMsg(m)
}

func _LedgerService_CreateLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ledger)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).CreateLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ledger.LedgerService/CreateLedger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).CreateLedger(ctx, req.(*Ledger))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_UpdateLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ledger)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).UpdateLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ledger.LedgerService/UpdateLedger",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).UpdateLedger(ctx, req.(*Ledger))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_SearchAccounts_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LedgerServiceServer).SearchAccounts(m, &ledgerServiceSearchAccountsServer{stream})
}

type LedgerService_SearchAccountsServer interface {
	Send(*Account) error
	grpc.ServerStream
}

type ledgerServiceSearchAccountsServer struct {
	grpc.ServerStream
}

func (x *ledgerServiceSearchAccountsServer) Send(m *Account) error {
	return x.ServerStream.SendMsg(m)
}

func _LedgerService_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ledger.LedgerService/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).CreateAccount(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ledger.LedgerService/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).UpdateAccount(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_SearchTransactions_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LedgerServiceServer).SearchTransactions(m, &ledgerServiceSearchTransactionsServer{stream})
}

type LedgerService_SearchTransactionsServer interface {
	Send(*Transaction) error
	grpc.ServerStream
}

type ledgerServiceSearchTransactionsServer struct {
	grpc.ServerStream
}

func (x *ledgerServiceSearchTransactionsServer) Send(m *Transaction) error {
	return x.ServerStream.SendMsg(m)
}

func _LedgerService_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ledger.LedgerService/CreateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).CreateTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_ReverseTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).ReverseTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ledger.LedgerService/ReverseTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).ReverseTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_UpdateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).UpdateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ledger.LedgerService/UpdateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).UpdateTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _LedgerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ledger.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLedger",
			Handler:    _LedgerService_CreateLedger_Handler,
		},
		{
			MethodName: "UpdateLedger",
			Handler:    _LedgerService_UpdateLedger_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _LedgerService_CreateAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _LedgerService_UpdateAccount_Handler,
		},
		{
			MethodName: "CreateTransaction",
			Handler:    _LedgerService_CreateTransaction_Handler,
		},
		{
			MethodName: "ReverseTransaction",
			Handler:    _LedgerService_ReverseTransaction_Handler,
		},
		{
			MethodName: "UpdateTransaction",
			Handler:    _LedgerService_UpdateTransaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SearchLedgers",
			Handler:       _LedgerService_SearchLedgers_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchAccounts",
			Handler:       _LedgerService_SearchAccounts_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SearchTransactions",
			Handler:       _LedgerService_SearchTransactions_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "ledger.proto",
}

func init() { proto.RegisterFile("ledger.proto", fileDescriptor_ledger_eb4c17c6264da805) }

var fileDescriptor_ledger_eb4c17c6264da805 = []byte{
	// 596 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x55, 0xd1, 0x6b, 0xd3, 0x5e,
	0x14, 0x5e, 0x9a, 0xac, 0x59, 0x4e, 0xdb, 0xfd, 0xb2, 0xf3, 0x53, 0xc9, 0x86, 0x42, 0x8d, 0x28,
	0x45, 0x74, 0xcc, 0x0e, 0x44, 0x86, 0x30, 0xe3, 0x9a, 0x87, 0x42, 0x9d, 0x23, 0xed, 0x40, 0x9f,
	0xc6, 0x5d, 0x7a, 0xd4, 0x61, 0x4d, 0xbb, 0xdb, 0x9b, 0x41, 0xfe, 0x55, 0xdf, 0x7c, 0xf5, 0x7f,
	0x10, 0x24, 0xf7, 0xde, 0x6c, 0x6d, 0x6c, 0x19, 0x1b, 0xfa, 0xd6, 0xef, 0xe6, 0x7c, 0xdf, 0xf9,
	0xbe, 0xc3, 0x39, 0x14, 0xea, 0x23, 0x1a, 0x7e, 0x26, 0xbe, 0x3d, 0xe1, 0x63, 0x31, 0xc6, 0xaa,
	0x42, 0xfe, 0x4b, 0x30, 0x83, 0x24, 0xc3, 0x4d, 0x58, 0x13, 0xd9, 0x84, 0x4e, 0x52, 0x3e, 0xf2,
	0x8c, 0xa6, 0xd1, 0x72, 0x22, 0x3b, 0xc7, 0xc7, 0x7c, 0x84, 0x77, 0x60, 0xf5, 0x82, 0x8d, 0x52,
	0xf2, 0x2a, 0x4d, 0xa3, 0x55, 0x8f, 0x14, 0xf0, 0x1f, 0x43, 0xa3, 0x4f, 0x8c, 0xc7, 0x5f, 0x22,
	0x3a, 0x4f, 0x69, 0x2a, 0xf2, 0xb2, 0xf3, 0x94, 0x78, 0xa6, 0xe9, 0x0a, 0xf8, 0xdf, 0x0d, 0xa8,
	0xf6, 0x64, 0x27, 0xbc, 0x0f, 0x0e, 0xa7, 0x4f, 0xc4, 0x29, 0x89, 0x49, 0x17, 0x5d, 0x3d, 0xe0,
	0x13, 0xb0, 0xf2, 0x86, 0xb2, 0xc9, 0x7a, 0x1b, 0xb7, 0xb5, 0x59, 0xc5, 0x1d, 0x64, 0x13, 0x8a,
	0xe4, 0x77, 0xbc, 0x07, 0xd5, 0x09, 0xe3, 0x94, 0x08, 0xcf, 0x94, 0x12, 0x1a, 0xe1, 0x33, 0xb0,
	0x86, 0x4c, 0x30, 0xcf, 0x6a, 0x9a, 0xad, 0x5a, 0xdb, 0x9b, 0xe7, 0x6f, 0x77, 0x98, 0x60, 0x61,
	0x22, 0x78, 0x16, 0xc9, 0xaa, 0xad, 0x0e, 0x38, 0x97, 0x4f, 0xe8, 0x82, 0xf9, 0x95, 0x0a, 0xdf,
	0xf9, 0x4f, 0x7c, 0x38, 0x1b, 0xb9, 0xd6, 0xae, 0x15, 0x6a, 0x41, 0x92, 0xe9, 0xfc, 0x7b, 0x95,
	0x57, 0x86, 0xff, 0xd3, 0x00, 0x3b, 0x88, 0xe3, 0x71, 0x9a, 0x88, 0x6b, 0xd2, 0x6d, 0xc1, 0x5a,
	0x9c, 0xf2, 0xfc, 0x77, 0x26, 0x35, 0x9d, 0xe8, 0x12, 0xe7, 0x89, 0x94, 0x7c, 0x91, 0x48, 0x21,
	0xf4, 0xc0, 0x3e, 0x65, 0x23, 0x96, 0xeb, 0x59, 0x4d, 0xa3, 0x65, 0x46, 0x05, 0xc4, 0xe7, 0x3a,
	0xeb, 0xaa, 0xcc, 0xba, 0x79, 0xe9, 0x4e, 0x59, 0xf9, 0x47, 0x61, 0x3b, 0xe0, 0x0e, 0x38, 0x4b,
	0xa6, 0x2c, 0x16, 0x67, 0xe3, 0x44, 0x89, 0x79, 0x60, 0x33, 0xd5, 0xb4, 0x58, 0x1a, 0x0d, 0xf3,
	0x50, 0xec, 0x9b, 0xfc, 0x50, 0x91, 0xde, 0x35, 0xf2, 0x7f, 0x19, 0x50, 0x9b, 0x91, 0xb9, 0x66,
	0x6c, 0x8f, 0xa0, 0x21, 0x74, 0x31, 0x0d, 0x4f, 0x98, 0xd0, 0xb3, 0xab, 0x5f, 0x3d, 0x06, 0x02,
	0x5f, 0xe8, 0x69, 0x98, 0x72, 0x1a, 0x0f, 0x0a, 0xfb, 0x33, 0x5d, 0xca, 0x13, 0xc1, 0x36, 0xd8,
	0x94, 0x08, 0x7e, 0x46, 0xd3, 0xf2, 0xbe, 0x94, 0x23, 0x46, 0x45, 0xe1, 0xdf, 0x99, 0xe2, 0xd3,
	0x1e, 0xc0, 0xd5, 0x4a, 0xa3, 0x03, 0xab, 0x41, 0xbf, 0x1f, 0x0e, 0xdc, 0x15, 0x6c, 0x80, 0xd3,
	0xeb, 0x06, 0x6f, 0xbb, 0xbd, 0xee, 0xe0, 0xa3, 0x6b, 0x20, 0x40, 0xb5, 0x7b, 0x78, 0xf0, 0xfe,
	0x5d, 0xe8, 0x56, 0xb0, 0x06, 0x76, 0xf8, 0xe1, 0x28, 0x3c, 0xec, 0x87, 0xae, 0x99, 0x83, 0x83,
	0xe0, 0xa8, 0x3b, 0x08, 0x7a, 0xae, 0xd5, 0xfe, 0x61, 0x41, 0x43, 0xc9, 0xf5, 0x89, 0x5f, 0x9c,
	0xc5, 0x84, 0x7b, 0xc5, 0x59, 0xaa, 0xe7, 0x29, 0xde, 0x2d, 0x8c, 0xcc, 0x5d, 0xeb, 0xd6, 0xfa,
	0xfc, 0x81, 0xf8, 0x2b, 0x3b, 0x06, 0xee, 0x40, 0xfd, 0x80, 0x13, 0x13, 0xa4, 0x0f, 0xb6, 0x54,
	0xf3, 0x27, 0x27, 0x67, 0x1c, 0x4f, 0x86, 0x37, 0x61, 0xbc, 0x86, 0x75, 0x65, 0x44, 0x2f, 0xeb,
	0x52, 0x83, 0xff, 0x95, 0xb6, 0x5a, 0x3a, 0xdc, 0x85, 0x86, 0x72, 0x58, 0x5c, 0x5d, 0xb9, 0x6a,
	0x01, 0x2d, 0x27, 0x29, 0x93, 0x37, 0x21, 0x75, 0x00, 0x95, 0x9f, 0x99, 0x85, 0x58, 0xea, 0xf5,
	0xff, 0x05, 0xdb, 0x23, 0xfd, 0xee, 0xc3, 0x86, 0xf2, 0x3b, 0xbb, 0xf2, 0x8b, 0xaa, 0x97, 0x48,
	0xe0, 0x1b, 0xc0, 0x88, 0x2e, 0x88, 0x4f, 0x6f, 0xad, 0xb0, 0x0f, 0x1b, 0x2a, 0xfd, 0x2d, 0x05,
	0x4e, 0xab, 0xf2, 0xff, 0x62, 0xf7, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xeb, 0xd1, 0x24,
	0x3f, 0x06, 0x00, 0x00,
}
